Update to API v1, SDK v2 and I3DF v6
cognitedata/3d-web-downloader pull request #3
Opened 2019-08-05 15:05 UTC by dragly

Also simplify the code a bit

2019-08-07 10:24 UTC, ghost requested changes

2019-08-07 10:24 UTC, dlcognite commented on package.json
> +    "@cognite/3d-web-parser": "../3d-web-parser/dragly/textures/",
uhhhh

2019-08-08 08:27 UTC, dragly commented on package.json
> +    "@cognite/3d-web-parser": "../3d-web-parser/dragly/textures/",
hmmm...

2019-08-08 08:36 UTC, ghost approved these changes

2019-08-09 15:14 UTC, merged